---
include:
  - board: eyelash_sofle_left
    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view_custom
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
